SHELL := /bin/bash

.PHONY: ship ship-dry ship-validate ship-ralph ship-memory ship-ci check prd-to-ralph scope

# ═══════════════════════════════════════════════════════════════════════════════
# GHOSTY SHIP-ALL WORKFLOW
# Run from terminal: make ship
# ═══════════════════════════════════════════════════════════════════════════════

# Check only requires STATUS.md - SCOPE.md is generated by agent
check:
	@bash scripts/util/require_files.sh STATUS.md
	@if [[ ! -f SCOPE.md ]]; then \
		echo "[CHECK] SCOPE.md not found. Run discovery phase first."; \
		echo "[CHECK] Agent generates SCOPE.md from conversation."; \
		exit 1; \
	fi

ship: check
	@bash scripts/ship.sh

ship-dry:
	@bash scripts/util/require_files.sh STATUS.md
	@DRY_RUN=1 bash scripts/ship.sh

ship-validate: check
	@bash scripts/validation/run_validation.sh

ship-ralph:
	@bash scripts/ralph/ralph.sh

ship-memory:
	@bash scripts/memory/memory.sh summary

ship-ci:
	@CI=1 bash scripts/ship.sh

# Generate SCOPE.md from JSON (called by agent)
# Usage: make scope JSON='{"product_type":"SaaS",...}'
scope:
	@bash scripts/util/generate_scope.sh --json '$(JSON)'

# Convert PRD markdown to Ralph stories
# Usage: make prd-to-ralph FEATURE=pdf-export NAME="PDF Export"
prd-to-ralph:
	@bash scripts/util/convert_prd_to_prdjson.sh tasks/tasks-$(FEATURE).md "$(NAME)"

ralph:
	@bash scripts/ralph/ralph.sh

# ═══════════════════════════════════════════════════════════════════════════════
# QUICK REFERENCE
# ═══════════════════════════════════════════════════════════════════════════════
# make scope JSON='{...}'  → Generate SCOPE.md (agent calls this)
# make ship                → Full pipeline (scope check → ralph → validate → memory)
# make ship-dry            → Print plan without executing
# make ship-validate       → Run only validation phase
# make ship-ralph          → Run only Ralph execution loop
# make ship-memory         → Show distilled learnings
# make prd-to-ralph        → Convert tasks/tasks-*.md to Ralph stories
# ═══════════════════════════════════════════════════════════════════════════════
