#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════════════════════
# GENERATE_SCOPE.SH
# Agent-driven SCOPE.md generator
# ═══════════════════════════════════════════════════════════════════════════════
# This script is called by the agent after discovery conversation.
# It takes structured input and produces SCOPE.md
#
# Usage: generate_scope.sh (interactive prompts)
#    or: generate_scope.sh --json '{"product_type":"SaaS",...}'
# ═══════════════════════════════════════════════════════════════════════════════

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

# If JSON provided, parse it
if [[ "${1:-}" == "--json" && -n "${2:-}" ]]; then
  JSON="$2"
  
  PRODUCT_TYPE="$(echo "$JSON" | jq -r '.product_type // "Web"')"
  MARKET="$(echo "$JSON" | jq -r '.market // "B2B"')"
  PERSONA="$(echo "$JSON" | jq -r '.persona // "SME"')"
  OUTCOME="$(echo "$JSON" | jq -r '.outcome // ""')"
  DELIVERABLES="$(echo "$JSON" | jq -r '.deliverables // [] | .[]' | sed 's/^/- /')"
  SUCCESS="$(echo "$JSON" | jq -r '.success_criteria // [] | .[]' | sed 's/^/- /')"
  CONTEXT="$(echo "$JSON" | jq -r '.context // ""')"
  CONSTRAINTS="$(echo "$JSON" | jq -r '.constraints // [] | .[]' | sed 's/^/- /')"
  
  cat > SCOPE.md << EOF
# SCOPE

> Auto-generated by agent during discovery phase.
> Last updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## Product Type
${PRODUCT_TYPE}

## Market
${MARKET}

## Target Persona
${PERSONA}

## Primary Outcome
${OUTCOME}

## Core Deliverables
${DELIVERABLES}

## Success Criteria
${SUCCESS}

## Context
${CONTEXT}

## Constraints
${CONSTRAINTS:-None specified}

---
*SCOPE LOCKED. Changes require new discovery cycle.*
EOF

  echo "[SCOPE] Generated SCOPE.md"
  echo "[SCOPE] Product Type: ${PRODUCT_TYPE}"
  echo "[SCOPE] Run 'make ship-dry' to verify pipeline."
  exit 0
fi

# Interactive mode (for manual use)
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "SCOPE GENERATOR (Interactive)"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "This should normally be called by the agent with --json flag."
echo "For manual use, answer the following:"
echo ""

read -p "Product Type (SaaS/Mobile/Web/API/Content): " PRODUCT_TYPE
read -p "Market (B2B/B2C/Internal/Hybrid): " MARKET
read -p "Target Persona (SME/Consumer/Enterprise/Developer/Creator): " PERSONA
read -p "Primary Outcome (1 sentence): " OUTCOME
echo "Core Deliverables (one per line, empty line to finish):"
DELIVERABLES=""
while IFS= read -r line; do
  [[ -z "$line" ]] && break
  DELIVERABLES="${DELIVERABLES}- ${line}"$'\n'
done
echo "Success Criteria (one per line, empty line to finish):"
SUCCESS=""
while IFS= read -r line; do
  [[ -z "$line" ]] && break
  SUCCESS="${SUCCESS}- ${line}"$'\n'
done

cat > SCOPE.md << EOF
# SCOPE

> Auto-generated by agent during discovery phase.
> Last updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## Product Type
${PRODUCT_TYPE}

## Market
${MARKET}

## Target Persona
${PERSONA}

## Primary Outcome
${OUTCOME}

## Core Deliverables
${DELIVERABLES}
## Success Criteria
${SUCCESS}
---
*SCOPE LOCKED. Changes require new discovery cycle.*
EOF

echo ""
echo "[SCOPE] Generated SCOPE.md"
